### ISSUE TITLE
support the ability to exclude the version prefix from the generated types

### ISSUE THREAD

**Issue by rotty3000** [yaacov/crdtoapi#6]
Because we prefer to put the version in the path which we can do simply by outputting the types to a sub-directory:

```shell
CRD_GV="group/v1"
npx crdtotypes --metadataType V1ObjectMeta -i ${OPENAPI_DIR}/openapi.yaml -o ${TYPESCRIPT_OUT_DIR}/${CRD_GV}
```

I'm thinking of a flag `--noApiVersionPrefix` so that the current behavior remains and allowing to opt-in to this new one.

PR forthcoming.

**Comment by yaacov** [comment]
https://www.npmjs.com/package/crdtoapi/v/0.0.18 :tada:

**Comment by yaacov** [comment]
https://www.npmjs.com/package/crdtoapi/v/0.0.19 :cake:

**Comment by rotty3000** [comment]
thank you @yaacov! :)
